### ISSUE TITLE
Showing the calendar instead of button?

### ISSUE THREAD

**Issue by swapnilahirwar28** [lekhmanrus/ngx-multiple-dates#10]
### Feature Description

Can we show the whole calendar instead of the toggle button?

**Comment by lekhmanrus** [comment]
Hi @swapnilahirwar28,
Thank you! Just released a new version, added documentation to [Readme](https://github.com/lekhmanrus/ngx-multiple-dates#calendar-inline) file and updated [Demo](https://lekhmanrus.github.io/ngx-multiple-dates/) page. 🙂
`mat-calendar` is supported now since [ngx-multiple-dates v14.2.0](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v14.2.0).

**Comment by swapnilahirwar28** [comment]
Thanks for the update.
