### ISSUE TITLE
Can Emit the chip removed Event?

### ISSUE THREAD

**Issue by IvanYCChen** [lekhmanrus/ngx-multiple-dates#11]
### Feature Description

Thanks for previous feature (chip date format).
This time, I want to do something when I remove chips, So can emit the chip removed Event?

**Comment by lekhmanrus** [comment]
Hi @IvanYCChen,
Thank you! Just released a new version, added documentation to [Readme](https://github.com/lekhmanrus/ngx-multiple-dates#multipledatescomponentd--date) file and updated [Demo](https://lekhmanrus.github.io/ngx-multiple-dates/) page (fires `console.log` output for **Simple** one). 🙂
Date removal event (from `chip` or `datepicker`) is supported now since [ngx-multiple-dates v14.3.0](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v14.3.0).

**Comment by IvanYCChen** [comment]
Thanks for the new feature

**Comment by IvanYCChen** [comment]
Hi
When I use the v14.3.0, I can't build the project.
Error message on below.
![2022-09-20 093154](https://user-images.githubusercontent.com/38700914/191147914-ca58d3e4-d9f3-481a-969f-7fed55b6ccaa.jpg)

**Comment by lekhmanrus** [comment]
Hi @IvanYCChen,
Thanks - just fixed that - please use [v14.3.1](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v14.3.1).

**Comment by IvanYCChen** [comment]
Thanks!!
Ssuccess to build my project.
