### ISSUE TITLE
Can add the new feature ?

### ISSUE THREAD

**Issue by FioneSilvaria** [lekhmanrus/ngx-multiple-dates#7]
### Feature Description

The chip date pipe can custom Format

**Comment by lekhmanrus** [comment]
Hi @FioneSilvaria,
Thank you! Just released a new version, added documentation to Readme file and updated [Demo](https://lekhmanrus.github.io/ngx-multiple-dates/) page. 🙂
Chip date formatting is supported now since [ngx-multiple-dates v14.1.0](https://github.com/lekhmanrus/ngx-multiple-dates/releases/tag/v14.1.0).
